version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: promocodefactory
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  webhost:
    build:
      context: ./Homeworks/EF/src
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY}/promocodefactory-webhost:${TAG}
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: promocodefactory
    volumes:
      - ./test-results:/app/TestResults

  tests:
    image: ghcr.io/${GITHUB_REPOSITORY}/promocodefactory-webhost:${TAG}
    depends_on:
      webhost:
        condition: service_started
    command: dotnet test --logger "trx;LogFileName=testresults.trx"
    volumes:
      - ./test-results:/app/TestResults