services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: promocodefactory
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  webhost:
    build:
      context: .
      dockerfile: docker-webhost.yml
    image: ghcr.io/orphey1974/asp.net/promocodefactory-webhost:${TAG}
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: promocodefactory
    volumes:
      - ./test-results:/app/TestResults

  tests:
    image: ghcr.io/orphey1974/asp.net/promocodefactory-webhost:${TAG}
    depends_on:
      webhost:
        condition: service_started
    command: dotnet test --logger "trx;LogFileName=testresults.trx"
    volumes:
      - ./test-results:/app/TestResults

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./PromoCodeFactory.WebHost:/app
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: promocodefactory
    command: sh -c "dotnet tool install --global dotnet-ef && dotnet build && ~/.dotnet/tools/dotnet-ef database update"
